### PR TITLE
Add support for books with lecterns. Allow signs/lecterns to be placed on any side to create a switch.

### PR DESCRIPTION
**Pull request by Longboyy**
Allows for using books/lecterns to specify destinations, as well as allowing signs and lecterns to be placed on any adjacent side to the detector rail

### CODE REVIEW

**Comment by Diet-Cola** [comment]
Have you tested this locally?

**Comment by Longboyy** [comment]
Yes this has been tested locally and confirmed to be working

**Review by grepsedawk — CHANGES_REQUESTED** [review]
This diff is unreadable and causes a large surface area for bugs.
Can you please prune this PR down to only the lines that need to change, so it's easier and safer to review and has less potential to cause unknown regressions?

**Comment by Diet-Cola** [comment]
@Longboyy Any update to this

**Comment by okx-code** [comment]
If you ever end up fixing the diff, please open this PR in https://github.com/CivMC/Civ

**Pull request closed without merging**
